### ISSUE TITLE
Unable to launch e2e tests using ionic 3.6.0

### ISSUE THREAD

**Issue by olivier-po** [joshuamorony/ionic-testing-elite-ionic#1]
For those who are running this issue.

I was unable to launch tests (npm run e2e) with the provided config using Ionic 3.6.0. The browser wouldn't launch and no test was being evaluated only the update of webdriver.

However, the repo : https://github.com/ionic-team/ionic-unit-testing-example was working correctly.

So I updated the package.json by adding those lines in the scripts key :
- "e2e-test": "protractor ./test-config/protractor.conf.js",
- "e2e-update": "webdriver-manager update --standalone false --gecko false"

And replacing
"e2e": "webdriver-manager update --standalone false --gecko false; protractor ./test-config/protractor.conf.js"
by
"e2e": "npm run e2e-update && npm run e2e-test",

It now works as intended

**Comment by ghost** [comment]
Also a solve for 3.9.2. Thanks.
